
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    image: nginx:1.0
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    image: wordpress:1.0
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1.0
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver_opts:
      device: /home/${USER}/data/mariadb
      o: bind
      type: none 
