FROM debian:bullseye

COPY ./conf/start.sh /mtg

RUN apt-get update && apt -y install curl wget netcat tar iputils-ping mariadb-client \
	&& apt -y install php php-fpm php-cli php-mysql php-gd php-xml php-curl \
	&& curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar && mv -f wp-cli.phar /usr/local/bin/wp

COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/

RUN mkdir /run/php

COPY ./conf/start.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start.sh

#RUN sed -i 's/^pid = \/run\/php\/php7\.3-fpm\.pid$/pid = \/var\/run\/php-fpm7.3.pid/' /etc/php/7.3/fpm/php-fpm.conf

ENTRYPOINT [ "./usr/local/bin/start.sh" ]


EXPOSE 9000 

#CMD ["sh", "-c", "./usr/local/bin/start.sh && /usr/sbin/php-fpm7.3 -F & tail -f /dev/null"]
CMD ["/usr/sbin/php-fpm7.3" "-F"]